#goal definition
string action
string boxId
string objId
string planGroup
geometry_msgs/PoseStamped pose
string predefined_pose_id
---
#result definition
int32 error_code
int32 cost
string armUsed
---
#feedback
int32 status